name: urbuzzi_app
description: "Urbuzzi - Gestão de Loteamentos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  intl: ^0.20.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  google_fonts: ^8.2.1
  url_launcher: ^6.2.5
  mask_text_input_formatter: ^2.9.0
  file_picker: ^11.0.3
  socket_io_client: ^3.1.6
  fl_chart: ^1.2.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.2.1
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  data_table_2: 2.3.12
  connectivity_plus: ^7.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^18.0.1
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: any

  freezed: ^3.2.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/mapa.svg
